"use client";

/**
 * GoogleIdentityButton — Google OAuth via Google Identity Services (GIS)
 *
 * Completely bypasses Firebase JS SDK. Uses Google's official GIS library:
 * 1. Google popup → returns ID token (JWT)
 * 2. POST ID token to /api/auth/firebase-bridge
 * 3. Bridge verifies via Firebase Admin SDK → returns signInToken
 * 4. NextAuth "firebase-token" provider creates session
 *
 * This eliminates ALL Firebase client SDK issues (bundle, version, config).
 */

import { useState } from "react";
import { signIn } from "next-auth/react";

// DATEASY DARK theme constants
const colors = {
  bg: "rgba(26, 26, 26, 0.9)",
  border: "rgba(85, 85, 85, 0.3)",
  borderHover: "rgba(76, 29, 149, 0.3)",
  text: "#ffffff",
  textLoading: "rgba(255,255,255,0.5)",
};

interface GoogleIdentityButtonProps {
  callbackUrl?: string;
  label?: string;
  disabled?: boolean;
  onError?: (error: string) => void;
}

// Google Icon (same as FirebaseOAuthButton)
function GoogleIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24">
      <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
      <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
      <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
      <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
    </svg>
  );
}

// Load Google Identity Services script
let gisLoaded = false;
let gisLoading = false;

function loadGIS(): Promise<void> {
  if (gisLoaded) return Promise.resolve();
  if (gisLoading) {
    return new Promise((resolve) => {
      const check = setInterval(() => {
        if (gisLoaded) { clearInterval(check); resolve(); }
      }, 100);
    });
  }

  gisLoading = true;
  return new Promise((resolve, reject) => {
    // Check if already loaded
    if ((window as any).google?.accounts) {
      gisLoaded = true;
      gisLoading = false;
      resolve();
      return;
    }

    const script = document.createElement("script");
    script.src = "https://accounts.google.com/gsi/client";
    script.async = true;
    script.defer = true;
    script.onload = () => {
      gisLoaded = true;
      gisLoading = false;
      resolve();
    };
    script.onerror = () => {
      gisLoading = false;
      reject(new Error("Failed to load Google Identity Services"));
    };
    document.head.appendChild(script);
  });
}

// Fetch Google OAuth Client ID from our config API
async function getGoogleClientId(): Promise<string> {
  const res = await fetch("/api/config/firebase");
  const data = await res.json();
  if (!data.valid || !data.config) {
    throw new Error("Firebase config not available");
  }
  // Google Client ID for this Firebase project
  // This is configured in Firebase Console → Authentication → Sign-in method → Google
  // The client ID is auto-generated by Firebase
  return "1054088598785-m8ln40j0ut8k5b2gn1hjbm1r0sbt9oj3.apps.googleusercontent.com";
}

export default function GoogleIdentityButton({
  callbackUrl = "/dashboard",
  label = "Continue with Google",
  disabled = false,
  onError,
}: GoogleIdentityButtonProps) {
  const [isLoading, setIsLoading] = useState(false);

  const handleSignIn = async () => {
    if (isLoading || disabled) return;
    setIsLoading(true);

    let bridgeRes: Response | null = null;
    let bridgeData: any = null;

    try {
      // Step 1: Load Google Identity Services
      await loadGIS();

      // Step 2: Get configuration
      const configRes = await fetch("/api/config/firebase");
      const configData = await configRes.json();
      if (!configData.valid) {
        throw new Error("Firebase config not available");
      }

      // Step 3: Initialize Google Identity Services token client
      const tokenClient = (window as any).google.accounts.oauth2.initTokenClient({
        client_id: "1054088598785-m8ln40j0ut8k5b2gn1hjbm1r0sbt9oj3.apps.googleusercontent.com",
        scope: "email profile",
        callback: async (response: any) => {
          // This callback is called after user selects their Google account
          try {
            if (response.error) {
              console.error("[GIS] Token error:", response);
              if (response.error === "popup_closed_by_user") {
                setIsLoading(false);
                return;
              }
              onError?.(`Google OAuth error: ${response.error}`);
              setIsLoading(false);
              return;
            }

            console.log("[GIS] Got ID token, sending to bridge...");

            // Step 4: Send ID token to our bridge API
            bridgeRes = await fetch("/api/auth/firebase-bridge", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ idToken: response.id_token }),
            });

            bridgeData = await bridgeRes.json();

            if (!bridgeRes.ok || !bridgeData.success) {
              throw new Error(bridgeData.error || "Bridge authentication failed");
            }

            console.log("[GIS] Bridge success, signing in via NextAuth...");

            // Step 5: Sign in via NextAuth
            const csrfRes = await fetch("/api/auth/csrf");
            const { csrfToken } = await csrfRes.json();

            if (!csrfToken) {
              throw new Error("Failed to get CSRF token");
            }

            const loginRes = await signIn("firebase-token", {
              token: bridgeData.signInToken,
              userId: bridgeData.userId,
              callbackUrl,
              csrfToken,
              redirect: false,
            });

            if (loginRes?.ok) {
              window.location.href = callbackUrl;
            } else {
              throw new Error(loginRes?.error || "NextAuth sign-in failed");
            }
          } catch (err: any) {
            console.error("[GIS] Flow error:", err);
            onError?.(err.message || "Google sign-in failed");
            setIsLoading(false);
          }
        },
      });

      // Step 3b: Request token (opens Google popup)
      console.log("[GIS] Requesting Google token...");
      tokenClient.requestAccessToken();
      // Note: the rest of the flow continues in the callback above
      // We do NOT set isLoading(false) here — the callback handles it

    } catch (error: any) {
      console.error("[GoogleIdentityButton] Error:", error);
      onError?.(error.message || "Google sign-in failed");
      setIsLoading(false);
    }
  };

  return (
    <button
      type="button"
      onClick={handleSignIn}
      disabled={isLoading || disabled}
      style={{
        padding: "13px 16px",
        background: colors.bg,
        border: `1px solid ${colors.border}`,
        borderRadius: "12px",
        color: isLoading ? colors.textLoading : colors.text,
        fontSize: "14px",
        fontWeight: "500",
        cursor: isLoading || disabled ? "not-allowed" : "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "8px",
        opacity: isLoading || disabled ? 0.5 : 1,
        transition: "all 0.2s",
        fontFamily: "'Outfit', sans-serif",
        width: "100%",
      }}
      onMouseEnter={(e) => {
        if (!isLoading && !disabled) e.currentTarget.style.borderColor = colors.borderHover;
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.borderColor = colors.border;
      }}
    >
      <GoogleIcon />
      {isLoading ? (
        <span style={{ display: "flex", alignItems: "center", gap: "6px" }}>
          <svg className="animate-spin" width="16" height="16" viewBox="0 0 24 24" fill="none">
            <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" strokeDasharray="32" strokeLinecap="round"/>
          </svg>
          Signing in...
        </span>
      ) : (
        label
      )}
    </button>
  );
}
